### PR TITLE
Add wrap files for rxcpp-4.1.0

### PR DESCRIPTION
**Pull request by meisenzahl**

### CODE REVIEW

**Comment by sarum9in** [comment]
Would you consider adding some tests also? It helps to make sure the library actually works.

**Comment by meisenzahl** [comment]
Do you have an example for adding tests? Where would I have to place them?

**Comment by sarum9in** [comment]
What I meant is there is a testing code in the project already: https://github.com/ReactiveX/RxCpp/tree/master/Rx/v2/test

You could hook it up with http://mesonbuild.com/Reference-manual.html#test
I don't know the structure of the project, maybe I am mistaken. But for a header-only library that would be nice.

**Comment by meisenzahl** [comment]
It's a bit complicated because RxCpp uses [catch2-2.4.1](https://github.com/mesonbuild/catch2/tree/2.4.1) for it's tests. There is a wrap file for catch2. But I think this way it would pollute the wrap for RxCpp because catch2 is only needed for it's tests. What is your opinion @sarum9in?

**Comment by sarum9in** [comment]
I don't have a strong opinion here. I would love to see something that verifies that the wrap actually works but if you think adding a dependency is not worth it I am not going to block on this. If all the tests depend on `catch2` then we can skip this I suppose.

**Comment by meisenzahl** [comment]
Thanks for your feedback. I created a repo for testing my implementation:

https://github.com/meisenzahl/rxcpp-wrap-test

Following the instructions you can verify that the tests are running. The meson build files are located in the folder `rxcpp`. For the tests I assume that RxCpp was checked out via git and that the git submodules are initialized.

Should I update the meson build definitions for the pull request accordingly?

**Comment by meisenzahl** [comment]
@sarum9in I added threads to the dependency list. Is there anything else I can do before it can be merged?

**Comment by sarum9in** [comment]
> For the tests I assume that RxCpp was checked out via git and that the git submodules are initialized.

No, sorry, I meant inline test by using original source code. That's fine, if it's too complicated to add them it's probably not worth.

**Pull request merged**
